# Generated by Django 2.2.6 on 2021-04-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210329_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Прикрепите изображение', null=True, upload_to='posts/', verbose_name='Изображение'),
        ),
    ]
